---
- name: Initialize and start project
  hosts: 127.0.0.1
  connection: local
  become: true

# Variables block
  vars_prompt:
    - name: main_domain
      prompt: "Enter main domain"
      private: false
      default: "example.com"
    - name: subdomain
      prompt: "Enter sub domain"
      private: false
      default: "example"
    - name: container
      prompt: "Enter container and port for nginx reverse proxy"
      private: false
      default: "example:8000"

# Validate entered variables
  pre_tasks:
    - name: Validate email
      fail:
        msg: >-
          Wrong email mask
      when: not email is regex('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
      run_once: true
# Tasks block
  tasks:
    # Create configs
    - set_fact:
        domain={{subdomain}}.{{main_domain}}
        container={{container}}
    - name: Create nginx config
      template:
        src: nginx/templates/sub_domain.conf
        dest: nginx/etc/nginx/conf.d/{{subdomain}}.{{main_domain}}.conf
    - name: Create ssl nginx config
      template:
        src: nginx/templates/ssl.sub_domain.conf.disabled
        dest: nginx/etc/nginx/conf.d/ssl.{{subdomain}}.{{main_domain}}.conf.disabled
    - name: Start nginx with old certs
      shell: bash nginx/one_domain_config.sh {{domain}}
      register: init_nginx
    - debug: var=init_nginx.stdout
