version: '3'

services:
  app:
    image: nextcloud-local-image
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextcloud
    restart: unless-stopped
    networks:
      nginx_net:
        ipv4_address: 172.20.0.3
    volumes:
      - ../data/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    entrypoint: sh -c '/wait-for-it.sh postgres:5432 --timeout=10 -- /entrypoint.sh apache2-foreground'

networks:
  nginx_net:
    external: true
