version: '3.7'

services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '$GITLAB_EXTERNAL_URL'
        nginx['listen_port'] = 9080
        nginx['listen_https'] = false
        letsencrypt['enabled'] = false
        # Reverse proxy nginx config
        nginx['redirect_http_to_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on",
          "Host" => "$GITLAB_HOST",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "Upgrade" => "$$http_upgrade",
          "Connection" => "$$connection_upgrade"
        }
    ports:
      - '9080:9080'
      - '23:22'
    volumes:
      - ../data/gitlab/config:/etc/gitlab
      - ../data/gitlab/logs:/var/log/gitlab
      - ../data/gitlab/data:/var/opt/gitlab
    networks:
      - gitlab

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - '../data/gitlab-runner/data:/home/gitlab_ci_multi_runner/data'
      - './config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    environment:
      - CI_SERVER_URL='$GITLAB_EXTERNAL_URL'/ci
    depends_on:
      - gitlab-web
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network
